<?php
/**
 * ReturnsStatusApi
 * PHP version 5
 *
 * @category Class
 * @package  EzzeSiftuz\ReturnsV2
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Returns Status Info API
 *
 * Returns Interface
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.16
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace EzzeSiftuz\ReturnsV2\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use EzzeSiftuz\ReturnsV2\ApiException;
use EzzeSiftuz\ReturnsV2\Configuration;
use EzzeSiftuz\ReturnsV2\HeaderSelector;
use EzzeSiftuz\ReturnsV2\ObjectSerializer;

/**
 * ReturnsStatusApi Class Doc Comment
 *
 * @category Class
 * @package  EzzeSiftuz\ReturnsV2
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ReturnsStatusApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation getPositionItemsForUsingGET
     *
     * Get all the items filtered on return status
     *
     * @param  string $authorization Access Token (required)
     * @param  string $status Return status for which items are being queried for (required)
     * @param  int $limit Page size to limit the number of items returned in the response. Maximum value for limit can 10 (optional)
     * @param  string $name name (optional)
     * @param  int $page Page number to fetch. This parameter is required to fetch data for specific page number (optional)
     *
     * @throws \EzzeSiftuz\ReturnsV2\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \EzzeSiftuz\ReturnsV2\Model\PositionItemList
     */
    public function getPositionItemsForUsingGET($authorization, $status, $limit = null, $name = null, $page = null)
    {
        list($response) = $this->getPositionItemsForUsingGETWithHttpInfo($authorization, $status, $limit, $name, $page);
        return $response;
    }

    /**
     * Operation getPositionItemsForUsingGETWithHttpInfo
     *
     * Get all the items filtered on return status
     *
     * @param  string $authorization Access Token (required)
     * @param  string $status Return status for which items are being queried for (required)
     * @param  int $limit Page size to limit the number of items returned in the response. Maximum value for limit can 10 (optional)
     * @param  string $name (optional)
     * @param  int $page Page number to fetch. This parameter is required to fetch data for specific page number (optional)
     *
     * @throws \EzzeSiftuz\ReturnsV2\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \EzzeSiftuz\ReturnsV2\Model\PositionItemList, HTTP status code, HTTP response headers (array of strings)
     */
    public function getPositionItemsForUsingGETWithHttpInfo($authorization, $status, $limit = null, $name = null, $page = null)
    {
        $returnType = '\EzzeSiftuz\ReturnsV2\Model\PositionItemList';
        $request = $this->getPositionItemsForUsingGETRequest($authorization, $status, $limit, $name, $page);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if (!in_array($returnType, ['string','integer','bool'])) {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EzzeSiftuz\ReturnsV2\Model\PositionItemList',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EzzeSiftuz\ReturnsV2\Model\ApiErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EzzeSiftuz\ReturnsV2\Model\ApiErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EzzeSiftuz\ReturnsV2\Model\ApiErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getPositionItemsForUsingGETAsync
     *
     * Get all the items filtered on return status
     *
     * @param  string $authorization Access Token (required)
     * @param  string $status Return status for which items are being queried for (required)
     * @param  int $limit Page size to limit the number of items returned in the response. Maximum value for limit can 10 (optional)
     * @param  string $name (optional)
     * @param  int $page Page number to fetch. This parameter is required to fetch data for specific page number (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getPositionItemsForUsingGETAsync($authorization, $status, $limit = null, $name = null, $page = null)
    {
        return $this->getPositionItemsForUsingGETAsyncWithHttpInfo($authorization, $status, $limit, $name, $page)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getPositionItemsForUsingGETAsyncWithHttpInfo
     *
     * Get all the items filtered on return status
     *
     * @param  string $authorization Access Token (required)
     * @param  string $status Return status for which items are being queried for (required)
     * @param  int $limit Page size to limit the number of items returned in the response. Maximum value for limit can 10 (optional)
     * @param  string $name (optional)
     * @param  int $page Page number to fetch. This parameter is required to fetch data for specific page number (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getPositionItemsForUsingGETAsyncWithHttpInfo($authorization, $status, $limit = null, $name = null, $page = null)
    {
        $returnType = '\EzzeSiftuz\ReturnsV2\Model\PositionItemList';
        $request = $this->getPositionItemsForUsingGETRequest($authorization, $status, $limit, $name, $page);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getPositionItemsForUsingGET'
     *
     * @param  string $authorization Access Token (required)
     * @param  string $status Return status for which items are being queried for (required)
     * @param  int $limit Page size to limit the number of items returned in the response. Maximum value for limit can 10 (optional)
     * @param  string $name (optional)
     * @param  int $page Page number to fetch. This parameter is required to fetch data for specific page number (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function getPositionItemsForUsingGETRequest($authorization, $status, $limit = null, $name = null, $page = null)
    {
        // verify the required parameter 'authorization' is set
        if ($authorization === null || (is_array($authorization) && count($authorization) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $authorization when calling getPositionItemsForUsingGET'
            );
        }
        // verify the required parameter 'status' is set
        if ($status === null || (is_array($status) && count($status) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $status when calling getPositionItemsForUsingGET'
            );
        }

        $resourcePath = '/v2/returns';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($limit !== null) {
            $queryParams['limit'] = ObjectSerializer::toQueryValue($limit);
        }
        // query params
        if ($name !== null) {
            $queryParams['name'] = ObjectSerializer::toQueryValue($name);
        }
        // query params
        if ($page !== null) {
            $queryParams['page'] = ObjectSerializer::toQueryValue($page);
        }
        // query params
        if ($status !== null) {
            $queryParams['status'] = ObjectSerializer::toQueryValue($status);
        }
        // header params
        if ($authorization !== null) {
            $headerParams['Authorization'] = ObjectSerializer::toHeaderValue($authorization);
        }


        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json;charset=UTF-8']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json;charset=UTF-8'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation receiveAcceptedReturnsV2UsingPOST
     *
     * Accept the return for a sent position item (up to 200 items per request)
     *
     * @param  \EzzeSiftuz\ReturnsV2\Model\AcceptedPartnerReturnV2 $body acceptedPartnerReturn (required)
     * @param  string $authorization Access Token (required)
     * @param  string $name name (optional)
     *
     * @throws \EzzeSiftuz\ReturnsV2\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return object
     */
    public function receiveAcceptedReturnsV2UsingPOST($body, $authorization, $name = null)
    {
        list($response) = $this->receiveAcceptedReturnsV2UsingPOSTWithHttpInfo($body, $authorization, $name);
        return $response;
    }

    /**
     * Operation receiveAcceptedReturnsV2UsingPOSTWithHttpInfo
     *
     * Accept the return for a sent position item (up to 200 items per request)
     *
     * @param  \EzzeSiftuz\ReturnsV2\Model\AcceptedPartnerReturnV2 $body acceptedPartnerReturn (required)
     * @param  string $authorization Access Token (required)
     * @param  string $name (optional)
     *
     * @throws \EzzeSiftuz\ReturnsV2\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of object, HTTP status code, HTTP response headers (array of strings)
     */
    public function receiveAcceptedReturnsV2UsingPOSTWithHttpInfo($body, $authorization, $name = null)
    {
        $returnType = 'object';
        $request = $this->receiveAcceptedReturnsV2UsingPOSTRequest($body, $authorization, $name);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if (!in_array($returnType, ['string','integer','bool'])) {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'object',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 207:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EzzeSiftuz\ReturnsV2\Model\AcceptedReturnMultiStatusResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EzzeSiftuz\ReturnsV2\Model\ApiErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 413:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EzzeSiftuz\ReturnsV2\Model\ApiErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EzzeSiftuz\ReturnsV2\Model\ApiErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation receiveAcceptedReturnsV2UsingPOSTAsync
     *
     * Accept the return for a sent position item (up to 200 items per request)
     *
     * @param  \EzzeSiftuz\ReturnsV2\Model\AcceptedPartnerReturnV2 $body acceptedPartnerReturn (required)
     * @param  string $authorization Access Token (required)
     * @param  string $name (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function receiveAcceptedReturnsV2UsingPOSTAsync($body, $authorization, $name = null)
    {
        return $this->receiveAcceptedReturnsV2UsingPOSTAsyncWithHttpInfo($body, $authorization, $name)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation receiveAcceptedReturnsV2UsingPOSTAsyncWithHttpInfo
     *
     * Accept the return for a sent position item (up to 200 items per request)
     *
     * @param  \EzzeSiftuz\ReturnsV2\Model\AcceptedPartnerReturnV2 $body acceptedPartnerReturn (required)
     * @param  string $authorization Access Token (required)
     * @param  string $name (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function receiveAcceptedReturnsV2UsingPOSTAsyncWithHttpInfo($body, $authorization, $name = null)
    {
        $returnType = 'object';
        $request = $this->receiveAcceptedReturnsV2UsingPOSTRequest($body, $authorization, $name);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'receiveAcceptedReturnsV2UsingPOST'
     *
     * @param  \EzzeSiftuz\ReturnsV2\Model\AcceptedPartnerReturnV2 $body acceptedPartnerReturn (required)
     * @param  string $authorization Access Token (required)
     * @param  string $name (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function receiveAcceptedReturnsV2UsingPOSTRequest($body, $authorization, $name = null)
    {
        // verify the required parameter 'body' is set
        if ($body === null || (is_array($body) && count($body) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $body when calling receiveAcceptedReturnsV2UsingPOST'
            );
        }
        // verify the required parameter 'authorization' is set
        if ($authorization === null || (is_array($authorization) && count($authorization) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $authorization when calling receiveAcceptedReturnsV2UsingPOST'
            );
        }

        $resourcePath = '/v2/returns/acceptance';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($name !== null) {
            $queryParams['name'] = ObjectSerializer::toQueryValue($name);
        }
        // header params
        if ($authorization !== null) {
            $headerParams['Authorization'] = ObjectSerializer::toHeaderValue($authorization);
        }


        // body params
        $_tempBody = null;
        if (isset($body)) {
            $_tempBody = $body;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json;charset=UTF-8']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json;charset=UTF-8'],
                ['application/json;charset=UTF-8']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation receiveRejectedReturnsV2UsingPOST
     *
     * Reject the return for a sent position item (up to 200 items per request)
     *
     * @param  \EzzeSiftuz\ReturnsV2\Model\RejectedPartnerReturnV2 $body rejectedPartnerReturn (required)
     * @param  string $authorization Access Token (required)
     * @param  string $name name (optional)
     *
     * @throws \EzzeSiftuz\ReturnsV2\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return object
     */
    public function receiveRejectedReturnsV2UsingPOST($body, $authorization, $name = null)
    {
        list($response) = $this->receiveRejectedReturnsV2UsingPOSTWithHttpInfo($body, $authorization, $name);
        return $response;
    }

    /**
     * Operation receiveRejectedReturnsV2UsingPOSTWithHttpInfo
     *
     * Reject the return for a sent position item (up to 200 items per request)
     *
     * @param  \EzzeSiftuz\ReturnsV2\Model\RejectedPartnerReturnV2 $body rejectedPartnerReturn (required)
     * @param  string $authorization Access Token (required)
     * @param  string $name (optional)
     *
     * @throws \EzzeSiftuz\ReturnsV2\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of object, HTTP status code, HTTP response headers (array of strings)
     */
    public function receiveRejectedReturnsV2UsingPOSTWithHttpInfo($body, $authorization, $name = null)
    {
        $returnType = 'object';
        $request = $this->receiveRejectedReturnsV2UsingPOSTRequest($body, $authorization, $name);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if (!in_array($returnType, ['string','integer','bool'])) {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'object',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 207:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EzzeSiftuz\ReturnsV2\Model\RejectedReturnMultiStatusResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EzzeSiftuz\ReturnsV2\Model\ApiErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 413:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EzzeSiftuz\ReturnsV2\Model\ApiErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EzzeSiftuz\ReturnsV2\Model\ApiErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation receiveRejectedReturnsV2UsingPOSTAsync
     *
     * Reject the return for a sent position item (up to 200 items per request)
     *
     * @param  \EzzeSiftuz\ReturnsV2\Model\RejectedPartnerReturnV2 $body rejectedPartnerReturn (required)
     * @param  string $authorization Access Token (required)
     * @param  string $name (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function receiveRejectedReturnsV2UsingPOSTAsync($body, $authorization, $name = null)
    {
        return $this->receiveRejectedReturnsV2UsingPOSTAsyncWithHttpInfo($body, $authorization, $name)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation receiveRejectedReturnsV2UsingPOSTAsyncWithHttpInfo
     *
     * Reject the return for a sent position item (up to 200 items per request)
     *
     * @param  \EzzeSiftuz\ReturnsV2\Model\RejectedPartnerReturnV2 $body rejectedPartnerReturn (required)
     * @param  string $authorization Access Token (required)
     * @param  string $name (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function receiveRejectedReturnsV2UsingPOSTAsyncWithHttpInfo($body, $authorization, $name = null)
    {
        $returnType = 'object';
        $request = $this->receiveRejectedReturnsV2UsingPOSTRequest($body, $authorization, $name);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'receiveRejectedReturnsV2UsingPOST'
     *
     * @param  \EzzeSiftuz\ReturnsV2\Model\RejectedPartnerReturnV2 $body rejectedPartnerReturn (required)
     * @param  string $authorization Access Token (required)
     * @param  string $name (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function receiveRejectedReturnsV2UsingPOSTRequest($body, $authorization, $name = null)
    {
        // verify the required parameter 'body' is set
        if ($body === null || (is_array($body) && count($body) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $body when calling receiveRejectedReturnsV2UsingPOST'
            );
        }
        // verify the required parameter 'authorization' is set
        if ($authorization === null || (is_array($authorization) && count($authorization) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $authorization when calling receiveRejectedReturnsV2UsingPOST'
            );
        }

        $resourcePath = '/v2/returns/rejection';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($name !== null) {
            $queryParams['name'] = ObjectSerializer::toQueryValue($name);
        }
        // header params
        if ($authorization !== null) {
            $headerParams['Authorization'] = ObjectSerializer::toHeaderValue($authorization);
        }


        // body params
        $_tempBody = null;
        if (isset($body)) {
            $_tempBody = $body;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json;charset=UTF-8']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json;charset=UTF-8'],
                ['application/json;charset=UTF-8']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
